[container.image]
repository="marconarde" # Docker hub name
name="orchestrator" # container name

[settings]
buildImage=true # you can make this false if you don't want to build the image and you just need the Dockerfile
singleYAML=true


[cloud.deployment]
min_memory="100Mi" # Minimum memory required for the container.
max_memory="256Mi" # Maximum memory a single container can take.
min_cpu="500m"  # Minimum CPU required for the container.
max_cpu="500m" # Maximum CPU a single container can take.
internal_domain_name="orchestrator" 
external_accessible=true

[cloud.deployment.autoscaling]
min_replicas=1 # Minimum number of container instances ran at a given time
max_replicas=3 # Maximum number of replicas of the container can scale up to
cpu=60 # Average CPU utilization of pods

# [[cloud.config.files]] # Mounts the `Config.toml` file as a config map in Kubernetes.
# file="./Config.toml"

# [cloud.deployment.probes.liveness]
# port=9091
# path="/probes/healthz"

# [cloud.deployment.probes.readiness]
# port=9091
# path="/probes/readyz"