apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server-deployment
  labels:
    app: game-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      containers:
      - name: game-server
        image: marconarde/gameserver:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: game-server-service
  labels:
    app: game-server
spec:
  selector:
    app: game-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
