apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking-deployment
  labels:
    app: matchmaking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaking
  template:
    metadata:
      labels:
        app: matchmaking
    spec:
      containers:
      - name: matchmaking
        image: marconarde/matchmaking:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: matchmaking-service
  labels:
    app: matchmaking
spec:
  selector:
    app: matchmaking
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
